# -*- coding: utf-8 -*-
"""Task_17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hTPty83BXSh2S07UYh_OnhjhyxoZj03

Student Name : Eaint Taryar Linlat

# Task 17 — Local Code Agent: Big Tech vs Big Banks Sharpe Ratio Analysis
**Module:** IB9AU — Advanced Machine Learning Applications

---

### Portfolios Under Analysis

| Sector | Tickers |
|--------|---------|
| Big Tech | NVDA, AAPL, MSFT |
| Big Banks | JPM, BAC, C |

### Sharpe Ratio Formula

```
Sharpe Ratio = (Mean Daily Return / Std Dev of Daily Returns) * sqrt(252)
```
Risk-free rate assumed = 0 (as specified in the task brief).

---

> **Runtime:** Set to **T4 GPU** before running.
> Runtime → Change runtime type → T4 GPU
> The 3B model uses ~6 GB VRAM — do not load other large models in the same session.

## Section 1 — Install Dependencies

| Package | Purpose |
|---------|--------|
| `smolagents` | Agent framework — CodeAgent orchestration |
| `transformers` + `accelerate` + `bitsandbytes` | Load Qwen 3B on GPU |
| `yfinance` | Download historical stock price data |
| `matplotlib` | Visualization (used by agent-generated code) |
| `pandas` + `numpy` | Data wrangling and maths |
"""

!pip install -q smolagents transformers accelerate bitsandbytes yfinance matplotlib pandas numpy
print('All dependencies installed.')

"""## Section 2 — Load the Local LLM (Qwen2.5-Coder-3B-Instruct)

`Qwen2.5-Coder-3B-Instruct` is a 3-billion-parameter model specialised for
code generation. At `float16` it fits comfortably in the T4's 16 GB VRAM
(~6 GB footprint) while being capable enough to write multi-step data-science
scripts from a plain-English prompt.

Key settings:
- `device_map='auto'` — automatically routes to the T4 GPU
- `torch_dtype=torch.float16` — halves memory vs full precision
- `max_new_tokens=2048` — enough budget for a complete multi-step script
"""

from smolagents import CodeAgent, TransformersModel
import torch

print('Downloading Qwen2.5-Coder-3B-Instruct (~6 GB, takes 2-3 min on first run)...')

model = TransformersModel(
    model_id='Qwen/Qwen2.5-Coder-3B-Instruct',
    device_map='auto',           # routes to T4 GPU automatically
    torch_dtype=torch.float16,   # half-precision to fit in 16 GB VRAM
    max_new_tokens=2048          # enough budget for a complete script
)

print('Model loaded on GPU and ready.')

"""## Section 3 — Initialise the Code Agent

We create a `CodeAgent` with **no pre-built tools** (`tools=[]`). This is the
key design choice: rather than giving the agent named functions to call (the
Gemini tool-use pattern from Task 16), we let it write its own complete Python
script from scratch.

`additional_authorized_imports` acts as a security sandbox — the agent can only
import the libraries we explicitly permit. We exclude `scipy` and `seaborn`
deliberately to keep the dependency footprint minimal and ensure the agent
computes Sharpe Ratios using pure NumPy rather than a black-box library.

`max_steps=4` gives the agent enough iterations to self-correct if it produces
a syntax error on the first attempt, without risking infinite loops that waste
GPU memory.
"""

agent = CodeAgent(
    tools=[],          # agent writes its own code — no pre-built tools
    model=model,
    max_steps=4,       # allows one self-correction pass if needed
    additional_authorized_imports=[
        'yfinance',           # stock data download
        'pandas',             # DataFrame operations
        'numpy',              # Sharpe Ratio maths
        'math',               # sqrt(252) annualisation
        'matplotlib.pyplot',  # bar chart generation
        'matplotlib.patches', # legend colour patches
    ]
)

print('CodeAgent initialised.')
print('  Tools       : none (agent generates its own code)')
print('  Max steps   : 4')
print('  Imports     : yfinance, pandas, numpy, math, matplotlib')

"""## Section 4 — The Task Prompt

This is the core of the task. A well-engineered prompt for a Code Agent must be:

- **Numbered and sequential** — code agents execute step-by-step; ambiguous
  ordering leads to incorrect variable references
- **Explicit about variable names** — telling the agent what to call its
  DataFrames and dictionaries prevents hallucinated names that break later steps
- **Restrictive about libraries** — specifying *which* library to use for each
  operation prevents the agent from importing something outside the sandbox
- **Precise about output format** — exact filename, DPI, and chart properties
  eliminate ambiguity about what 'done' looks like

The prompt below encodes all of these principles. Each numbered step maps
cleanly to a block of Python code the agent will generate.
"""

task_prompt = """
You are a quantitative analyst. Write a single, complete, self-contained Python
script that performs the following steps. Use ONLY these libraries:
yfinance, pandas, numpy, math, matplotlib.pyplot, matplotlib.patches.
Do NOT import scipy, seaborn, or any other library.

Step 1 — Download data:
    Use yfinance to download daily closing prices for the last 180 trading days
    for all six tickers at once:
        tickers = ['NVDA', 'AAPL', 'MSFT', 'JPM', 'BAC', 'C']
    Use: df = yf.download(tickers, period='180d', auto_adjust=True)['Close']
    Ensure the result is a DataFrame with the ticker symbols as column names.
    Drop any rows with missing values.

Step 2 — Daily returns:
    Calculate daily percentage returns for each stock:
        returns = df.pct_change().dropna()

Step 3 — Annualised Sharpe Ratio:
    For each ticker, compute the annualised Sharpe Ratio assuming a risk-free
    rate of zero:
        sharpe_ratio = (mean_daily_return / std_daily_return) * math.sqrt(252)
    Store the results in a dict named sharpe_dict where keys are ticker strings
    and values are the Sharpe Ratio floats.

Step 4 — Colour coding:
    Define:
        tech  = ['NVDA', 'AAPL', 'MSFT']
        banks = ['JPM', 'BAC', 'C']
    Build a list named bar_colors where each element is 'green' if the
    corresponding ticker (in the order of sharpe_dict.keys()) is in tech,
    or 'blue' if it is in banks.

Step 5 — Bar chart:
    Create a bar chart with these exact properties:
    - Figure size: (10, 6)
    - X-axis: ticker symbols (sharpe_dict.keys())
    - Y-axis: Sharpe Ratio values (sharpe_dict.values())
    - Bar colours: bar_colors list
    - Bar edge colour: black, linewidth 0.8
    - Title: 'Annualised Sharpe Ratio: Big Tech vs Big Banks (Last 180 Days)'
    - X-axis label: 'Stock Ticker'
    - Y-axis label: 'Annualised Sharpe Ratio (risk-free rate = 0)'
    - Add a horizontal dashed grey line at y=0 (zero Sharpe reference)
    - Annotate each bar with its Sharpe Ratio value rounded to 2 decimal places,
      centred above the bar
    - Add a legend with two patches:
        green patch labelled 'Big Tech (NVDA, AAPL, MSFT)'
        blue  patch labelled 'Big Banks (JPM, BAC, C)'

Step 6 — Save and print:
    Save the chart as 'sharpe_comparison.png' with dpi=150 and bbox_inches='tight'.
    Print each ticker and its Sharpe Ratio rounded to 4 decimal places.
    Print which sector (Tech or Banks) has the higher average Sharpe Ratio.
"""

print('Task prompt defined. Ready to run the agent.')

"""## Section 5 — Run the Agent

Calling `agent.run()` starts the ReAct loop. Watch the output below to see
the agent's **Thought → Code → Observation** cycle as it:

1. Plans the script structure
2. Writes and executes Python code
3. Reads any error output and self-corrects if needed
4. Reports the final result

The `[TOOL]` / `[STEP]` markers in the log show each iteration of the loop.
Typical runtime on a T4: **60–120 seconds**.
"""

print('Agent starting — watch the Thought/Code/Observation loop below...')
print('=' * 65)

result = agent.run(task_prompt, stream=False)

print('=' * 65)
print('Agent finished.')

# Print the agent's final summary output
print('AGENT FINAL OUTPUT:')
print(result)

"""## Section 6 — Display the Sharpe Ratio Chart

If the agent successfully saved `sharpe_comparison.png`, we render it inline.
If not, the fallback message explains where to look for errors in the log above.
"""

import IPython.display
import os

if os.path.exists('sharpe_comparison.png'):
    print('Displaying Sharpe Ratio Comparison Chart:')
    IPython.display.display(IPython.display.Image('sharpe_comparison.png'))
else:
    print('sharpe_comparison.png not found.')
    print('Check the agent log above for errors and re-run Section 5.')

"""## Section 7 — Fallback: Direct Python Script

If the agent fails to produce the chart after `max_steps=4`, run this cell
directly. It executes the same logic that the agent was instructed to write,
giving us the output without relying on the LLM's code generation.

This cell is **independent of the agent** — it will always work as long as
`yfinance` and `matplotlib` are installed.

> Skip this cell if the agent already produced `sharpe_comparison.png`.
"""

# ── Fallback: run this cell directly if the agent did not produce the chart ──
import yfinance as yf
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ---- Step 1: Download 180 days of closing prices --------------------------
TICKERS = ['NVDA', 'AAPL', 'MSFT', 'JPM', 'BAC', 'C']

print('Downloading 180 days of closing prices...')
df = yf.download(TICKERS, period='180d', auto_adjust=True)['Close']
df = df.dropna()
print(f'Downloaded {len(df)} trading days for {list(df.columns)}')

# ---- Step 2: Daily percentage returns -------------------------------------
returns = df.pct_change().dropna()

# ---- Step 3: Annualised Sharpe Ratio (risk-free rate = 0) -----------------
sharpe_dict = {}
for ticker in TICKERS:
    mean_ret = returns[ticker].mean()
    std_ret  = returns[ticker].std()
    sharpe   = (mean_ret / std_ret) * math.sqrt(252)
    sharpe_dict[ticker] = round(sharpe, 4)

print('\nSharpe Ratios (annualised, rf=0):')
for t, s in sharpe_dict.items():
    sector = 'Tech ' if t in ['NVDA','AAPL','MSFT'] else 'Banks'
    print(f'  [{sector}] {t:4s} : {s:.4f}')

# ---- Sector averages -------------------------------------------------------
tech_avg  = np.mean([sharpe_dict[t] for t in ['NVDA','AAPL','MSFT']])
banks_avg = np.mean([sharpe_dict[t] for t in ['JPM','BAC','C']])
winner    = 'Big Tech' if tech_avg > banks_avg else 'Big Banks'
print(f'\nAvg Tech Sharpe  : {tech_avg:.4f}')
print(f'Avg Banks Sharpe : {banks_avg:.4f}')
print(f'Better risk-adjusted performance: {winner}')

# ---- Step 4: Colour coding ------------------------------------------------
TECH  = ['NVDA', 'AAPL', 'MSFT']
BANKS = ['JPM', 'BAC', 'C']
bar_colors = ['green' if t in TECH else 'blue' for t in sharpe_dict.keys()]

# ---- Step 5: Bar chart ----------------------------------------------------
fig, ax = plt.subplots(figsize=(10, 6))

bars = ax.bar(
    sharpe_dict.keys(),
    sharpe_dict.values(),
    color=bar_colors,
    edgecolor='black',
    linewidth=0.8,
    width=0.55
)

# Zero-reference line
ax.axhline(0, color='grey', linestyle='--', linewidth=0.9, alpha=0.7)

# Annotate bars with Sharpe values
for bar, val in zip(bars, sharpe_dict.values()):
    y_pos = bar.get_height() + (0.03 if val >= 0 else -0.07)
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        y_pos,
        f'{val:.2f}',
        ha='center', va='bottom', fontsize=10, fontweight='bold'
    )

ax.set_title(
    'Annualised Sharpe Ratio: Big Tech vs Big Banks (Last 180 Days)',
    fontsize=13, fontweight='bold', pad=14
)
ax.set_xlabel('Stock Ticker', fontsize=11)
ax.set_ylabel('Annualised Sharpe Ratio (risk-free rate = 0)', fontsize=11)

# Sector average reference lines
ax.axhline(tech_avg,  color='green', linestyle=':', linewidth=1.2,
           label=f'Tech avg = {tech_avg:.2f}')
ax.axhline(banks_avg, color='blue',  linestyle=':', linewidth=1.2,
           label=f'Banks avg = {banks_avg:.2f}')

# Legend
tech_patch  = mpatches.Patch(color='green', label='Big Tech (NVDA, AAPL, MSFT)')
banks_patch = mpatches.Patch(color='blue',  label='Big Banks (JPM, BAC, C)')
ax.legend(handles=[tech_patch, banks_patch], fontsize=10, loc='upper right')

plt.tight_layout()
plt.savefig('sharpe_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

print('Chart saved as sharpe_comparison.png')

# Display the fallback chart
import IPython.display, os
if os.path.exists('sharpe_comparison.png'):
    IPython.display.display(IPython.display.Image('sharpe_comparison.png'))

"""---
## Section 8 — Reflection: Insights from Building a Local Code Agent

### The Code Agent vs Tool-Use Agent Distinction

Task 16 used Gemini with named tool functions — the LLM *decided which function
to call*, but never wrote or executed code itself. This task uses a fundamentally
different paradigm: the local Code Agent *writes a complete Python script* and
executes it in a sandboxed subprocess. The LLM's output is not a string answer
but runnable code. This makes Code Agents far more flexible — they can perform
arbitrary computations, not just pre-defined operations — but also more brittle:
a small syntax error in generated code causes execution failure rather than a
graceful degradation.

### Prompt Engineering for Code Generation

The single most important finding from this task is that **prompt specificity
directly determines code correctness**. An under-specified prompt like
*'compare Sharpe Ratios for Tech and Banks'* causes the agent to make ambiguous
choices: which library for the download? What column name does `yf.download`
return? What exactly is 'annualised'? Each ambiguity is a potential point of
failure. The structured prompt in Section 4 eliminates these by specifying
exact variable names (`sharpe_dict`, `bar_colors`), the precise download call
(`yf.download(tickers, period='180d', auto_adjust=True)['Close']`), and
the exact Sharpe formula. The agent's self-correction capability (`max_steps=4`)
provides a safety net, but a precise prompt reduces the need for it.

### The Importance of the Fallback Cell

Small models (3B parameters) occasionally fail to generate correct code on
complex multi-step tasks, particularly when the output involves both numerical
computation and matplotlib figure management. The fallback cell in Section 7
is not just a debugging aid — it is a production design pattern. In any
real agentic system, the generated code should be accompanied by a
deterministic reference implementation that can be used for output validation
and as a fallback when the agent fails.

### Interpreting Sharpe Ratios

A Sharpe Ratio above 1.0 is generally considered good; above 2.0, excellent.
Negative Sharpe Ratios indicate the stock underperformed the risk-free asset
over the measured period. Because we set the risk-free rate to zero, any
positive Sharpe means the stock delivered positive risk-adjusted returns.
The 180-day window captures approximately one half-year of price action —
long enough to smooth short-term noise but short enough that the results
are sensitive to specific market events (earnings surprises, rate decisions,
sector rotations). A more robust analysis would use rolling Sharpe Ratios
across multiple time windows.

### Why Local Models Matter

Running Qwen2.5-Coder-3B locally — rather than via a cloud API — means:
- **No data leaves the runtime**: financial data and any proprietary prompts
  stay entirely within the Colab session
- **No per-token cost**: the model runs on the free T4 GPU
- **No rate limits**: the agent can retry and self-correct without hitting
  API quotas

The trade-off is capability: a 3B model makes more code errors than GPT-4
or Gemini 2.5. For constrained, well-specified tasks like this one, the
quality gap is manageable with a good prompt and a fallback cell.
"""