# -*- coding: utf-8 -*-
"""Task_14_Visual_RAG_AstraZeneca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0w2Co1vUEh17GdVnWs2WS0SE8twmxoA

# Task 14 - Page-Wise Visual RAG for AstraZeneca Q4/FY 2025 Earnings Report

**Module:** IB9AU - Advanced Machine Learning Applications  
**Task:** Required Task 14  
**Runtime:** Google Colab - T4 GPU

---

## What This Notebook Does

Traditional text-based RAG systems fail on financial PDFs because tables,
footnotes, and multi-column layouts get scrambled during text extraction.
This notebook implements a **Page-Wise Visual RAG** pipeline that sidesteps
that problem entirely:

1. **Embed** each page's extracted text with `all-MiniLM-L6-v2` for fast semantic search.
2. **Retrieve** the single most relevant page for a user query.
3. **Render** that PDF page to a pixel image (bypassing fragile text extraction).
4. **Prompt** `Qwen2.5-VL-3B-Instruct` with the image + question, letting it *see*
   the tables exactly as a human financial analyst would.

This mirrors a real analyst workflow: **find the right page, then read it carefully**.

---

### Architecture at a Glance

```
User Query
    |
    v
[MiniLM Embeddings] --> [LlamaIndex Vector Store]
                               |
                         retrieve top-1 page
                               |
                    [pdf2image @ 150 DPI]
                               |
              +----------------+----------------+
              |   Page Image (PIL)              |
              +----------------+----------------+
                               |
                  [Qwen2.5-VL-3B-Instruct]
                  (image + text prompt -> answer)
                               |
                               v
                       Structured Answer
```

---

### Setup Checklist
- [ ] Runtime > Change runtime type > **T4 GPU**
- [ ] Upload `AstraZeneca-Q4-2025-earnings.pdf`
- [ ] Run cells **in order** (Step 1 requires a runtime restart)

---
## Step 1 - Fix Pillow (Run Once, Then Restart Runtime)

Google Colab ships with Pillow 9.x. The HuggingFace `sentence-transformers`
library triggers an `ImportError: cannot import name '_Ink'` with that version.
Upgrading to Pillow >= 10 resolves it.

> **Instructions:** run the cell below, then go to **Runtime > Restart session**.
> Continue from Step 2 onwards. Do **not** re-run this cell after restarting.
"""

# Step 1: Upgrade Pillow to fix the '_Ink' ImportError
# Run ONCE, then restart the runtime before continuing.

!pip install -qU Pillow

print('Pillow upgraded.')
print('Now go to: Runtime > Restart session, then continue from Step 2.')

"""---
## Step 2 - Confirm GPU and Install All Dependencies

After the runtime restarts, run this cell. It checks for a T4 GPU, then
installs the full dependency stack.

| Package | Role |
|---------|------|
| `transformers` + `accelerate` | Load and run Qwen2.5-VL on GPU |
| `llama-index-*` | PDF loading, embedding, vector index, retrieval |
| `pdf2image` + `poppler-utils` | Render PDF pages to PIL images |
| `pypdf` | Read PDF metadata (page count, labels) |

"""

# Step 2: GPU check + dependency installation

import torch

# --- GPU availability check ---
if torch.cuda.is_available():
    gpu_name = torch.cuda.get_device_name(0)
    vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f'GPU detected : {gpu_name}')
    print(f'VRAM         : {vram_gb:.1f} GB')
else:
    print('NO GPU DETECTED')
    print('-> Runtime > Change runtime type > T4 GPU, then re-run.')
    raise RuntimeError('T4 GPU required. Change runtime type and retry.')

# --- Install all packages ---
print('\nInstalling packages (takes ~2 min on first run)...')

!pip install -qU transformers accelerate
!pip install -qU llama-index-core llama-index-readers-file llama-index-embeddings-huggingface pypdf
!pip install -qU pdf2image
!apt-get install -qq poppler-utils

print('\nAll dependencies installed successfully.')

"""---
## Step 3 - Upload the AstraZeneca PDF

Place `AstraZeneca-Q4-2025-earnings.pdf` in the Colab working directory.
The cell below checks automatically; if missing, it opens a file-upload widget.

"""

# Step 3: Locate or upload the AstraZeneca PDF
import os

PDF_PATH = 'AstraZeneca-Q4-2025-earnings.pdf'

if os.path.exists(PDF_PATH):
    size_kb = os.path.getsize(PDF_PATH) / 1024
    print(f'PDF found: {PDF_PATH}  ({size_kb:.0f} KB)')
else:
    print(f'{PDF_PATH} not found -- opening upload widget...')
    from google.colab import files
    uploaded = files.upload()
    if PDF_PATH not in uploaded:
        # Accept any PDF if the name differs slightly
        candidates = [k for k in uploaded if k.lower().endswith('.pdf')]
        if candidates:
            PDF_PATH = candidates[0]
            print(f'Using: {PDF_PATH}')
        else:
            raise FileNotFoundError('No PDF file was uploaded.')
    size_kb = os.path.getsize(PDF_PATH) / 1024
    print(f'PDF ready: {PDF_PATH}  ({size_kb:.0f} KB)')

# Sanity-check: count pages
from pypdf import PdfReader
n_pages = len(PdfReader(PDF_PATH).pages)
print(f'Pages in document: {n_pages}')

"""---
## Step 4 - Load the Sentence-Transformer Embedding Model

`sentence-transformers/all-MiniLM-L6-v2` converts text into 384-dimensional
vectors for semantic similarity search. It runs entirely on CPU and requires
no API key -- essential for cost-free retrieval on Colab's free tier.

**Why this model?**
- Very small (22 MB) -- loads in seconds
- Strong semantic similarity on short passages (ideal for page-level chunks)
- Widely benchmarked on financial and technical text

"""

# Step 4: Load the embedding model
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

EMBED_MODEL_ID = 'sentence-transformers/all-MiniLM-L6-v2'

print(f'Loading embedding model: {EMBED_MODEL_ID}')
embed_model = HuggingFaceEmbedding(model_name=EMBED_MODEL_ID)
print('Embedding model ready (384-dim, CPU).')

# Smoke test -- verify the model produces 384-dim vectors
test_vec = embed_model.get_text_embedding('AstraZeneca total revenue FY 2025')
print(f'Smoke-test embedding dimension: {len(test_vec)}')  # should be 384

"""---
## Step 5 - Load Qwen2.5-VL-3B-Instruct (Vision-Language Model)

`Qwen2.5-VL-3B-Instruct` is a 3-billion-parameter open-source vision-language
model that accepts both images and text, making it ideal for reading rendered
PDF pages that contain mixed tables, charts, and prose.

**Memory at `float16`:** ~6-7 GB -- fits comfortably within T4's 16 GB VRAM.

**Why `device_map='cuda'` instead of `'auto'`?**  
`'auto'` can silently place layers on CPU when multiple devices are visible,
causing a 10x slowdown. Explicitly setting `'cuda'` guarantees GPU-only
inference and makes performance predictable.

"""

# Step 5: Load the Qwen2.5-VL vision-language model onto the GPU
import torch
from transformers import Qwen2_5_VLForConditionalGeneration, AutoProcessor

VLM_MODEL_ID = 'Qwen/Qwen2.5-VL-3B-Instruct'

print(f'Loading {VLM_MODEL_ID} ...')
print('(First run downloads ~6 GB -- takes 2-3 minutes)')

vlm_model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    VLM_MODEL_ID,
    torch_dtype=torch.float16,  # half-precision to fit in T4 VRAM
    device_map='cuda',          # force GPU -- avoids silent CPU fallback
)
vlm_processor = AutoProcessor.from_pretrained(VLM_MODEL_ID)

# Confirm placement and VRAM usage
model_device = next(vlm_model.parameters()).device
vram_used_gb = torch.cuda.memory_allocated() / 1e9

print(f'VLM loaded on  : {model_device}')
print(f'VRAM in use    : {vram_used_gb:.1f} GB')

if str(model_device) == 'cpu':
    print('WARNING: model is on CPU -- each query will take 5-10 minutes!')

"""---
## Step 6 - Configure LlamaIndex and Build the Vector Index

LlamaIndex handles **retrieval only** here. We set `Settings.llm = None` to
stop it from calling an external LLM for generation (Qwen handles that).

`SimpleDirectoryReader` loads the PDF as **one Document per page**, each
carrying `page_label` metadata. We build a `VectorStoreIndex` backed by
our MiniLM embeddings, then create a retriever with `similarity_top_k=1`
to return only the single best-matching page per query.

**Why `top_k=1`?**  
Passing multiple page images to Qwen2.5-VL would exceed GPU memory for
image tokens. One well-chosen page, read visually, typically outperforms
several text-extracted fragments concatenated together.

"""

# Step 6: Build the page-level vector index
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex, Settings

# Point LlamaIndex at our embedding model; disable its built-in LLM
Settings.embed_model = embed_model
Settings.llm         = None
print('LlamaIndex configured (embed=MiniLM, llm=None).')

# Load the PDF -- creates one Document per page with page_label metadata
print(f'\nLoading PDF pages from: {PDF_PATH}')
documents = SimpleDirectoryReader(input_files=[PDF_PATH]).load_data()
print(f'Loaded {len(documents)} page documents.')
print(f'Example metadata : {documents[0].metadata}')
print(f'Example text     : {documents[0].text[:200]!r}')

# Build in-memory vector store and retriever
print('\nBuilding vector index over all pages...')
index     = VectorStoreIndex.from_documents(documents)
retriever = index.as_retriever(similarity_top_k=1)
print('Index ready -- retriever configured for top-1 page retrieval.')

"""---
## Step 7 - Define the Visual RAG Query Function

`query_visual_rag()` runs the full pipeline in five stages:

| Stage | What happens |
|-------|--------------|
| **Retrieve** | MiniLM embeds the query; cosine similarity finds best page |
| **Locate** | `page_label` metadata gives us the 1-based page number |
| **Render** | `pdf2image` rasterises that page at 150 DPI |
| **Prompt** | Chat template wraps image + analyst instructions + question |
| **Generate** | Qwen2.5-VL runs greedy decoding for deterministic output |

**Key design choices:**
- `dpi=150` -- readable for small table text; higher DPI doubles memory use.
- `do_sample=False` + `temperature=None` -- financial extraction should be
  deterministic; stochastic sampling introduces unnecessary variance.
- The system prompt explicitly instructs the model to cite the table or
  section it reads from, enabling downstream verification.

"""

# Step 7: The Visual RAG orchestrator function
import time
from pdf2image import convert_from_path
from PIL import Image
from IPython.display import display, Markdown


def query_visual_rag(query: str,
                     max_new_tokens: int = 300,
                     show_page: bool = True) -> str:
    """
    Page-Wise Visual RAG pipeline.

    Parameters
    ----------
    query          : Natural-language question about the AstraZeneca report.
    max_new_tokens : Token budget for the VLM response (~10-12 s per 300 on T4).
    show_page      : Display the retrieved page image inline if True.

    Returns
    -------
    str : The VLM's answer as a plain string.
    """
    SEP = '=' * 65
    print(SEP)
    print(f'QUERY  : {query}')
    print(SEP)
    t0 = time.time()

    # ---- Stage 1: Retrieve best-matching page ----------------------------
    nodes = retriever.retrieve(query)
    if not nodes:
        return 'No relevant pages found in the index.'

    best       = nodes[0]
    page_label = best.metadata.get('page_label', '1')
    page_idx   = int(page_label) - 1   # 0-based for pdf2image
    sim_score  = best.score

    print(f'\n[1/5] RETRIEVE  -> Page {page_label}  (similarity: {sim_score:.4f})')
    print(f'       Snippet  : {best.text[:120].strip()}...')

    # ---- Stage 2: Locate -------------------------------------------------
    print(f'[2/5] LOCATE    -> 0-based page index: {page_idx}')

    # ---- Stage 3: Render PDF page as an image ----------------------------
    print(f'[3/5] RENDER    -> Rasterising page {page_label} at 150 DPI...')
    rendered = convert_from_path(
        PDF_PATH,
        first_page=page_idx + 1,
        last_page =page_idx + 1,
        dpi=150,
    )
    page_image = rendered[0]
    w, h = page_image.size
    print(f'       Image size : {w} x {h} px')

    if show_page:
        dw = 620
        dh = int(dw * h / w)
        print(f'\n--- Retrieved Page {page_label} ---')
        display(page_image.resize((dw, dh), Image.LANCZOS))

    # ---- Stage 4: Build multimodal prompt --------------------------------
    print(f'\n[4/5] PROMPT    -> Formatting Qwen2.5-VL chat messages...')

    system_ctx = (
        f'You are a meticulous financial analyst reviewing Page {page_label} '
        'of the AstraZeneca FY and Q4 2025 Earnings Report. '
        'Answer only from content visible on this page -- tables, text, and charts. '
        'Quote exact figures and always cite the specific table number or section '
        'heading you are reading from. '
        'If a table is partially visible, state that clearly.'
    )

    messages = [
        {
            'role': 'user',
            'content': [
                {'type': 'image', 'image': page_image},
                {'type': 'text',  'text': f'{system_ctx}\n\nQuestion: {query}'},
            ],
        }
    ]

    text_prompt = vlm_processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = vlm_processor(
        text=[text_prompt],
        images=[page_image],
        return_tensors='pt',
    ).to(vlm_model.device)

    # ---- Stage 5: Generate -----------------------------------------------
    print(f'[5/5] GENERATE  -> Running Qwen2.5-VL (max {max_new_tokens} tokens)...')

    with torch.no_grad():
        output_ids = vlm_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,   # greedy decoding -> deterministic output
            temperature=None,  # must be None when do_sample=False
            top_p=None,        # same
        )

    # Decode only the newly generated tokens (exclude the input prompt)
    new_tokens = output_ids[:, inputs['input_ids'].shape[1]:]
    answer = vlm_processor.batch_decode(new_tokens, skip_special_tokens=True)[0]

    elapsed = time.time() - t0
    print(f'\nCompleted in {elapsed:.1f} s')
    print(SEP)
    return answer


print('query_visual_rag() defined and ready.')
print('Typical latency on T4: ~10-15 s per query.')

"""---
---
# Tasks

The three required queries follow, each exercising a different
analytical capability of the Visual RAG system.

---

## Task 1 - Revenue Table Extraction

**Query:**  
*"What were AstraZeneca's total Product Sales and Alliance Revenue for FY 2025,
and how did each change compared to FY 2024?"*

**Why visual RAG outperforms text-only RAG here:**  
Financial revenue tables use multi-column layouts where percentage-change columns
sit far from their row headers. Standard PDF text extraction flattens those
columns into a single stream, breaking the header-to-value relationship.
A VLM reading the rendered page sees the table in its original spatial form --
exactly as a human analyst would.
"""

# Task 1: Revenue Table Extraction

QUERY_1 = (
    'What were AstraZenecas total Product Sales and Alliance Revenue '
    'for FY 2025, and how did each change compared to FY 2024?'
)

display(Markdown('### Task 1 - Revenue Table Extraction'))
display(Markdown(f'**Query:** *{QUERY_1}*'))
display(Markdown('---'))

answer_1 = query_visual_rag(QUERY_1, max_new_tokens=350)

display(Markdown('### VLM Answer - Task 1'))
display(Markdown(answer_1))

"""---
## Task 2 - Regional Revenue Breakdown

**Query:**  
*"Which geographic region had the highest Total Revenue growth in FY 2025,
and what was the growth rate at constant exchange rates?"*

**Why this requires visual understanding:**  
Regional breakdowns are presented as a table with rows for Emerging Markets,
Europe, Established Rest of World, and the US, each with separate columns for
reported and constant-exchange-rate (CER) growth. Identifying the maximum
across rows requires comparing values across the full table layout -- a
multi-step reasoning task that benefits from the intact spatial structure
that a rendered image preserves.

"""

# Task 2: Regional Revenue Breakdown

QUERY_2 = (
    'Which geographic region had the highest Total Revenue growth in FY 2025, '
    'and what was the growth rate at constant exchange rates?'
)

display(Markdown('### Task 2 - Regional Revenue Breakdown'))
display(Markdown(f'**Query:** *{QUERY_2}*'))
display(Markdown('---'))

answer_2 = query_visual_rag(QUERY_2, max_new_tokens=350)

display(Markdown('### VLM Answer - Task 2'))
display(Markdown(answer_2))

"""---
## Task 3 - R&D Pipeline Interpretation

**Query:**  
*"Which medicines received regulatory approvals in the US between
November 2025 and February 2026, and for what indications?"*

**Why this is hard for text-only extraction:**  
R&D pipeline pages are among the densest in any pharma earnings report.
They combine structured tables with colour-coded phase indicators, footnotes,
and abbreviated indication names. Filtering by both geography (US) and date
range (Nov 2025 - Feb 2026) requires the model to read across multiple columns
simultaneously -- a form of timeline comprehension that is extremely brittle
after PDF-to-text conversion because table cells frequently merge or shift.

"""

# Task 3: R&D Pipeline Interpretation

QUERY_3 = (
    'Which medicines received regulatory approvals in the US between '
    'November 2025 and February 2026, and for what indications?'
)

display(Markdown('### Task 3 - R&D Pipeline Interpretation'))
display(Markdown(f'**Query:** *{QUERY_3}*'))
display(Markdown('---'))

answer_3 = query_visual_rag(QUERY_3, max_new_tokens=400)

display(Markdown('### VLM Answer - Task 3'))
display(Markdown(answer_3))

"""---
## Task 4 - Audit Mode Query

This task requires designing an **original audit-style prompt** that:
- Targets a section **different** from Tasks 1-3
- Demands precise numerical figures
- Explicitly instructs the VLM to cite page and table number
- Is followed by manual verification of at least two specific figures

### Chosen Target: Reported-to-Core Reconciliation (Table 10)

I selected the **Reported-to-Core reconciliation table** rather than the cash
flow statement because it is a particularly demanding test case:

1. It bridges two accounting frames (Reported IFRS vs Core non-GAAP), so any
   hallucinated adjustment would create an internally inconsistent reconciliation.
2. The adjustments subtable contains numerous specific line items (restructuring,
   intangible amortisation, etc.) that are easy to cross-check individually.
3. It tests whether the VLM can navigate a multi-level nested table with
   subtotals -- a layout that frequently confuses text parsers.

**Audit design principle:**  
By requiring the model to state the exact table number and page for every figure,
we create a verifiable chain of custody. Each number has a stated provenance
that can be physically confirmed in the rendered page image.

"""

# Task 4: Audit Mode -- Reported-to-Core Reconciliation (Table 10)

QUERY_4 = (
    'AUDIT MODE - Table 10 (Reported-to-Core Reconciliation): '
    'For FY 2025 and FY 2024, report the following items: '
    '(1) Reported Operating Profit, '
    '(2) Total adjustments to reach Core Operating Profit, '
    '(3) Core Operating Profit, and '
    '(4) Core Operating Profit Margin as a percentage of Core Revenue. '
    'Present all dollar values in USD millions. '
    'For every figure, state the exact table number and page you are reading from. '
    'Format as a side-by-side comparison of FY 2025 vs FY 2024.'
)

display(Markdown('### Task 4 - Audit Mode: Reported-to-Core Reconciliation'))
display(Markdown(f'**Query:** *{QUERY_4}*'))
display(Markdown('---'))

answer_4 = query_visual_rag(QUERY_4, max_new_tokens=500)

display(Markdown('### VLM Answer - Task 4'))
display(Markdown(answer_4))

"""---
### Task 4 - Verification

After obtaining the VLM's answer, we re-render the retrieved page at higher
resolution (200 DPI) to allow careful manual cross-checking of at least two
stated figures against the source document.

"""

# Task 4: Manual verification -- re-render the page and check figures
print('=' * 65)
print('TASK 4 - VERIFICATION STAGE')
print('=' * 65)

# Identify the page that was retrieved for the audit query
audit_nodes = retriever.retrieve(QUERY_4)
audit_page  = audit_nodes[0].metadata.get('page_label', '?')
audit_score = audit_nodes[0].score

print(f'\nPage retrieved for audit query : Page {audit_page}')
print(f'Similarity score               : {audit_score:.4f}')
print(f'Text preview                   : {audit_nodes[0].text[:200].strip()}...')

# Render at 200 DPI for comfortable visual inspection of small table text
print(f'\nRendering Page {audit_page} at 200 DPI for verification...')
verify_idx  = int(audit_page) - 1
verify_imgs = convert_from_path(
    PDF_PATH,
    first_page=verify_idx + 1,
    last_page =verify_idx + 1,
    dpi=200,
)
verify_img = verify_imgs[0]
dw = 720
dh = int(dw * verify_img.height / verify_img.width)

print(f'\n--- Page {audit_page} (verification render at 200 DPI) ---')
display(verify_img.resize((dw, dh), Image.LANCZOS))

# Structured verification checklist
print('\n' + '=' * 65)
print('VERIFICATION CHECKLIST')
print('=' * 65)
print("""
Compare each figure the VLM reported against the rendered page above.

[CHECK] Figure 1 - Reported Operating Profit (FY 2025):
    VLM stated   : [see answer above]
    Source shows : [read from page image]
    Match?       : YES / NO / PARTIAL

[CHECK] Figure 2 - Core Operating Profit (FY 2025):
    VLM stated   : [see answer above]
    Source shows : [read from page image]
    Match?       : YES / NO / PARTIAL

[CHECK] Figure 3 - Core Operating Profit Margin (FY 2025):
    VLM stated   : [see answer above]
    Source shows : [read from page image]
    Match?       : YES / NO / PARTIAL

Notes:
- Record any discrepancies and distinguish rounding differences
  from genuine hallucinations.
- If the VLM cited an incorrect table number, note that too.
""")

"""---
---
## Summary and Reflections

### Results Overview

| Task | Query Focus | Visual RAG Capability |
|------|-------------|----------------------|
| 1 | Product Sales & Alliance Revenue, FY2025 vs FY2024 | Multi-column table reading, YoY delta extraction |
| 2 | Regional revenue -- highest CER growth rate | Row-by-row comparison across geographic segments |
| 3 | US regulatory approvals, Nov 2025 - Feb 2026 | Timeline filtering + entity extraction from dense pipeline table |
| 4 | Reported-to-Core reconciliation, Table 10 | Audit-grade extraction with citation and manual verification |

---

### Key Architectural Decisions

**Why page-level chunking rather than paragraph-level?**  
Financial PDFs package information spatially: a table header, its rows, and
explanatory footnotes all appear on the same page. Splitting into paragraphs
destroys that spatial relationship. Keeping each page as one chunk means the
VLM receives the full spatial context needed to interpret tables correctly.

**Why `similarity_top_k=1`?**  
Passing multiple page images would exceed Qwen2.5-VL's image token budget
and VRAM limits. One well-chosen page, seen visually, outperforms several
degraded text fragments. The MiniLM retriever is accurate enough that the
correct page is almost always ranked first for specific financial queries.

**Why greedy decoding (`do_sample=False`)?**  
Financial extraction is not a creative task. We need the same answer every
time for a given image and query. Stochastic sampling would make audit
verification unreliable and introduce unnecessary variance.

**Why 150 DPI for queries and 200 DPI for verification?**  
150 DPI renders an A4 page at roughly 1240 pixels wide -- enough for Qwen
to read table text while keeping image memory reasonable. The verification
render uses 200 DPI so a human can inspect small footnote text comfortably.

---

### Limitations and Potential Improvements

1. **Single-page retrieval** -- Queries spanning two adjacent pages (e.g.
   a table that breaks across a page boundary) will miss the continuation.
   A `top_k=2` fallback with careful image batching could help.

2. **OCR-quality dependence** -- The MiniLM retriever embeds the text that
   PyPDF extracts. If the PDF was scanned rather than digitally generated,
   extraction quality is poor and retrieval suffers. A pre-processing OCR
   step (e.g. Tesseract or PaddleOCR) before indexing would improve this.

3. **VLM hallucination risk** -- Small VLMs occasionally generate plausible
   but incorrect figures, especially for numbers partially obscured or in
   complex nested tables. The audit verification step in Task 4 exists
   precisely to surface this. In production, all extracted figures should
   be cross-checked by a secondary extraction method (e.g. camelot-py).

4. **Query sensitivity** -- Phrasing matters: 'Product Revenue' and 'Product
   Sales' may retrieve different pages depending on exact document wording.
   HyDE (Hypothetical Document Embeddings) or query expansion could improve
   retrieval robustness for ambiguously worded financial queries.

"""